server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: first-server
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888

springdoc:
  api-docs:
    path: /s1/v3/api-docs
  packages-to-scan: com.hanhwa_tae.firstserver
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8